spring:
#  datasource:
#    # 如果有使用 Atomikos，則要加 pinGlobalTxToPhysicalConnection=true，否則會出現 XAER_INVAL: Invalid arguments (or unsupported command)
#    url: jdbc:mysql://34.81.9.0/IPETDB?pinGlobalTxToPhysicalConnection=true
#    username: root
#    password: Coco40725eee.S1225.abc
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    type: com.zaxxer.hikari.HikariDataSource
#
#    # 解決（springboot項目）mysql表名大寫，造成jpa Table doesn't exist問題
#    jpa:
#      hibernate:
#        naming:
#          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  data:
    mongodb:
      uri: mongodb://root:abc123Coco@34.81.9.0:27017/ipetdb?authSource=admin
      username: root
      password: abc123Coco
  thymeleaf:
    cache: false

  mvc:
    hiddenmethod:
      filter:
        enabled: true
  cloud:
    gcp:
      credentials:
        location: classpath:ipetproject-1f8092e65534.json
      project-id: IPetProject
gcp:
  bucketName: ipet_bucket



