version: '3'
services:
  mongodb:
    image: mongo
    container_name: m_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - "./dbdata:/var/lib/mongodb"
    command: mongod --auth
    environment:
      - MONGO_INITDB_DATABASE=ipetdb
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=Coco40725eee.S1225.abc